### ISSUE TITLE
crash when importing same excel file twice

### ISSUE THREAD

**Issue by niklasmohrin** [fsr-de/EvaP#1397] opened 2019-12-16 20:59 UTC
When uploading and importing the same excel file twice, the site crashes:

`IntegrityError at /staff/semester/21/import
duplicate key value violates unique constraint "evaluation_course_temp_semester_id_name_en_1b4b4c6a_uniq"
DETAIL:  Key (semester_id, name_en)=(21, Build) already exists.`

The UI does not suggest any error in the file.

**Comment by He3lixxx** [comment] 2020-01-06 19:08
This happens because we are not correctly checking whether a course with this english or german name already exists. This, this is a duplicate of #1390.

**Closed by He3lixxx** 2020-01-06 19:08 UTC
